"""OpenClaw deployer — deploy OpenClaw instances on a VPS in Docker.

This service:
1. Generates a Docker Compose file for the OpenClaw stack.
2. SSHs into the target VPS and deploys the stack.
3. Returns the public URL of the running OpenClaw instance.
"""

import os
import uuid
import asyncio
import tempfile
from typing import Optional

OPENCLAW_IMAGE = os.getenv("OPENCLAW_IMAGE", "openclaw/openclaw:latest")
OPENCLAW_INTERNAL_PORT = 9000
OPENCLAW_MOCK_MODE = os.getenv("OPENCLAW_MOCK_MODE", "").lower() in ("1", "true", "yes")
HIVE_URL = os.getenv("HIVE_URL", "http://localhost:8080")
# Base domain for per-agent subdomains. If set, each agent gets {slug}.{HIVE_DOMAIN}.
# nginx + certbot will be configured automatically on the VPS.
HIVE_DOMAIN = os.getenv("HIVE_DOMAIN", "")
# Path to the existing wildcard or SAN cert to reuse (avoids certbot per deploy).
# If empty, certbot will try to issue a cert for the specific subdomain.
HIVE_SSL_CERT = os.getenv("HIVE_SSL_CERT", "")
HIVE_SSL_KEY = os.getenv("HIVE_SSL_KEY", "")


def generate_compose(
    instance_id: str,
    agent_name: str,
    agent_id: str,
    api_key: str,
    port: int = 9000,
    extra_env: Optional[dict] = None,
    config_env: Optional[dict] = None,
) -> str:
    """Return a docker-compose.yml string for an OpenClaw instance.

    extra_env: arbitrary env vars passed at deploy time (user model API keys, etc.)
    config_env: per-agent config (LLM keys, integration tokens) stored in Hive DB.

    Secret values (``*_API_KEY`` / ``*_SECRET`` / ``*_TOKEN``) are NOT written
    into the compose file. Instead they are written to ``./secrets/<NAME>`` on
    the remote host and mounted read-only into the container as files, exposed
    to the runtime via ``<NAME>_FILE`` env vars — so they never appear in
    ``docker inspect`` or in this file.
    """
    from services.secrets import split_secrets

    merged = {**(extra_env or {}), **(config_env or {})}
    plain, secrets = split_secrets(merged)

    env_lines = ""
    for k, v in plain.items():
        env_lines += f"      - {k}={v}\n"
    # Expose each secret's file path to the runtime (file is written + mounted
    # by deploy_to_vps). The agent reads it via ``<NAME>_FILE``.
    secret_defs = ""
    secret_mounts = ""
    secret_refs = ""
    for name in secrets:
        fname = name.lower()
        secret_defs += f"  {fname}:\n    file: ./secrets/{fname}\n"
        secret_mounts += f"      - {fname}:/run/secrets/{fname}:ro\n"
        secret_refs += f"      - {name}_FILE=/run/secrets/{fname}\n"

    # Use build: . when no custom image is set (default) so we build from
    # the Dockerfile shipped to the remote dir alongside this compose file.
    if OPENCLAW_IMAGE and OPENCLAW_IMAGE != "openclaw/openclaw:latest":
        image_or_build = f"image: {OPENCLAW_IMAGE}"
    else:
        image_or_build = "build: ."

    return f"""\
# Auto-generated by Hive — OpenClaw instance {instance_id}
services:
  openclaw-{instance_id[:8]}:
    {image_or_build}
    container_name: openclaw-{instance_id[:8]}
    restart: unless-stopped
    ports:
      - "127.0.0.1:{port}:{OPENCLAW_INTERNAL_PORT}"
    environment:
      - INSTANCE_ID={instance_id}
      - AGENT_ID={agent_id}
      - AGENT_NAME={agent_name}
      - HIVE_API_KEY={api_key}
      - HIVE_URL={HIVE_URL}
{env_lines}{secret_refs}    labels:
      hive.managed: "true"
      hive.instance-id: "{instance_id}"
      hive.agent-name: "{agent_name}"
    networks:
      - default
      - hive-net
    secrets:
{secret_mounts}    networks:
      - default
      - hive-net

secrets:
{secret_defs}networks:
  hive-net:
    external: true
"""


async def deploy_to_vps(
    vps_host: str,
    ssh_key_path: str,
    compose_content: str,
    instance_id: str,
    port: int,
    ssh_user: str = "root",
    ssh_port: int = 22,
    agent_slug: Optional[str] = None,
    extra_env: Optional[dict] = None,
    config_env: Optional[dict] = None,
) -> dict:
    """
    Deploy an OpenClaw Docker Compose stack to a remote VPS via SSH.

    Returns:
        dict with keys: success, message, url (if success)
    """
    remote_dir = f"/opt/hive/openclaw-{instance_id[:8]}"

    if OPENCLAW_MOCK_MODE:
        return {
            "success": True,
            "message": "OpenClaw deployed successfully (mock mode)",
            "url": f"http://{vps_host}:{port}",
            "remote_dir": remote_dir,
        }

    # Write compose to a temp file to scp it over
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".yml", delete=False
    ) as tmp:
        tmp.write(compose_content)
        local_compose = tmp.name

    ssh_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -p {ssh_port}"
    )
    scp_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -P {ssh_port}"
    )
    target = f"{ssh_user}@{vps_host}"

    # Locate the docker/ directory shipped with Hive (relative to this file).
    _svc_dir = os.path.dirname(__file__)
    _docker_dir = os.path.normpath(os.path.join(_svc_dir, "..", "..", "docker"))

    try:
        # 1. Create remote directory
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} 'mkdir -p {remote_dir}'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {
                "success": False,
                "message": f"Failed to create remote dir: {stderr.decode()}",
            }

        # 2. Copy compose file
        proc = await asyncio.create_subprocess_shell(
            f"scp {scp_opts} {local_compose} {target}:{remote_dir}/docker-compose.yml",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {
                "success": False,
                "message": f"Failed to copy compose file: {stderr.decode()}",
            }

        # 2b. Copy Dockerfile + agent_app so the remote can do `docker build`.
        #     We always ship these — they're small and ensure the container has
        #     the correct /delegate endpoint.
        if os.path.isdir(_docker_dir):
            proc = await asyncio.create_subprocess_shell(
                f"scp {scp_opts} -r "
                f"{_docker_dir}/Dockerfile.openclaw "
                f"{_docker_dir}/agent_app "
                f"{target}:{remote_dir}/",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await proc.communicate()
            if proc.returncode != 0:
                return {
                    "success": False,
                    "message": f"Failed to copy Dockerfile: {stderr.decode()}",
                }
            # Rename Dockerfile.openclaw → Dockerfile for `docker build .`
            proc = await asyncio.create_subprocess_shell(
                f"ssh {ssh_opts} {target} "
                f"'mv {remote_dir}/Dockerfile.openclaw {remote_dir}/Dockerfile'",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            await proc.communicate()

        # 2c. Write secret values to files on the remote host. These are
        # mounted read-only into the container by the compose `secrets:` block
        # so the keys never appear in `docker inspect` or in the compose file.
        from services.secrets import split_secrets
        _, secret_values = split_secrets({**(extra_env or {}), **(config_env or {})})
        if secret_values:
            # Create the secrets dir remotely.
            proc = await asyncio.create_subprocess_shell(
                f"ssh {ssh_opts} {target} 'mkdir -p {remote_dir}/secrets'",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await proc.communicate()
            if proc.returncode != 0:
                return {
                    "success": False,
                    "message": f"Failed to create secrets dir: {stderr.decode()}",
                }
            for name, value in secret_values.items():
                fname = name.lower()
                # Write the secret via a heredoc so it never hits a shell arg/log.
                cmd = (
                    f"ssh {ssh_opts} {target} "
                    f"'cat > {remote_dir}/secrets/{fname} <<EOF\n{value}\nEOF'"
                )
                proc = await asyncio.create_subprocess_shell(
                    cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
                )
                _, stderr = await proc.communicate()
                if proc.returncode != 0:
                    return {
                        "success": False,
                        "message": f"Failed to write secret {name}: {stderr.decode()}",
                    }
            # Lock down permissions on the secrets dir.
            proc = await asyncio.create_subprocess_shell(
                f"ssh {ssh_opts} {target} 'chmod -R 600 {remote_dir}/secrets'",
                stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
            )
            await proc.communicate()

        # 3. Build + start container
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} "
            f"'cd {remote_dir} && docker compose build && docker compose up -d'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {
                "success": False,
                "message": f"docker compose up failed: {stderr.decode()}",
            }

        # Provision nginx subdomain + SSL if domain is configured
        dashboard_url = f"http://{vps_host}:{port}"
        if HIVE_DOMAIN and agent_slug:
            subdomain_result = await _provision_nginx_subdomain(
                ssh_opts=ssh_opts,
                scp_opts=scp_opts,
                target=target,
                slug=agent_slug,
                port=port,
            )
            if subdomain_result.get("url"):
                dashboard_url = subdomain_result["url"]

        return {
            "success": True,
            "message": "OpenClaw deployed successfully",
            "url": f"http://{vps_host}:{port}",
            "dashboard_url": dashboard_url,
            "remote_dir": remote_dir,
        }

    except Exception as e:
        return {"success": False, "message": str(e)}

    finally:
        os.unlink(local_compose)


async def _provision_nginx_subdomain(
    ssh_opts: str,
    scp_opts: str,
    target: str,
    slug: str,
    port: int,
) -> dict:
    """
    Create an nginx server block for {slug}.{HIVE_DOMAIN} → localhost:{port}
    and provision an SSL cert via certbot.

    Uses the existing hive.rajeev.me cert if HIVE_SSL_CERT / HIVE_SSL_KEY are
    set (wildcard case). Otherwise falls back to certbot --nginx.
    The dashboard is proxied via Hive at /a/{slug}/ so nginx points to Hive (port 8080),
    not directly to the container — this keeps authentication in place.
    """
    subdomain = f"{slug}.{HIVE_DOMAIN}"
    # Proxy to Hive's authenticated dashboard proxy, not directly to the container.
    # Parse the port from HIVE_URL safely; fall back to 8080 when no explicit port
    # is present (e.g. https://hive.rajeev.me has no port in the URL).
    from urllib.parse import urlparse as _urlparse
    _parsed_hive = _urlparse(HIVE_URL)
    hive_port = _parsed_hive.port or 8080

    # If a wildcard cert is configured reuse it; otherwise run certbot
    if HIVE_SSL_CERT and HIVE_SSL_KEY:
        ssl_block = f"""
    ssl_certificate {HIVE_SSL_CERT};
    ssl_certificate_key {HIVE_SSL_KEY};"""
        needs_certbot = False
    else:
        ssl_block = f"""
    ssl_certificate /etc/letsencrypt/live/{subdomain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{subdomain}/privkey.pem;"""
        needs_certbot = True

    nginx_conf = f"""\
server {{
    listen 80;
    server_name {subdomain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl;
    server_name {subdomain};
{ssl_block}

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {{
        proxy_pass http://127.0.0.1:{hive_port}/a/{slug}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host {HIVE_DOMAIN};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_cache_bypass $http_upgrade;
    }}
}}
"""
    conf_path = f"/etc/nginx/sites-available/{slug}.conf"
    enabled_path = f"/etc/nginx/sites-enabled/{slug}.conf"

    try:
        # Write nginx config via heredoc over SSH
        with tempfile.NamedTemporaryFile(mode="w", suffix=".conf", delete=False) as tmp:
            tmp.write(nginx_conf)
            local_conf = tmp.name

        proc = await asyncio.create_subprocess_shell(
            f"scp {scp_opts} {local_conf} {target}:{conf_path}",
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        os.unlink(local_conf)
        if proc.returncode != 0:
            return {"url": None, "error": f"Failed to write nginx config: {stderr.decode()}"}

        # Enable site + test + reload nginx
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} "
            f"'ln -sf {conf_path} {enabled_path} && nginx -t && nginx -s reload'",
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {"url": None, "error": f"nginx reload failed: {stderr.decode()}"}

        # Run certbot if needed (non-blocking best-effort)
        if needs_certbot:
            proc = await asyncio.create_subprocess_shell(
                f"ssh {ssh_opts} {target} "
                f"'certbot --nginx -d {subdomain} --non-interactive "
                f"--agree-tos --email admin@{HIVE_DOMAIN} --redirect 2>&1 | tail -5'",
                stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
            )
            stdout, _ = await proc.communicate()
            if proc.returncode != 0:
                # Certbot failed (often DNS not yet propagated) — nginx still works over HTTP
                return {
                    "url": f"https://{subdomain}",
                    "note": f"Nginx configured but certbot failed: {stdout.decode()[:200]}. "
                            "SSL may not be active yet — retry once DNS propagates.",
                }

        return {"url": f"https://{subdomain}"}

    except Exception as e:
        return {"url": None, "error": str(e)}


async def teardown_on_vps(
    vps_host: str,
    ssh_key_path: str,
    instance_id: str,
    ssh_user: str = "root",
    ssh_port: int = 22,
) -> dict:
    """Tear down (stop + remove) an OpenClaw instance on a remote VPS."""
    remote_dir = f"/opt/hive/openclaw-{instance_id[:8]}"
    ssh_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -p {ssh_port}"
    )
    target = f"{ssh_user}@{vps_host}"

    try:
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} "
            f"'cd {remote_dir} && docker compose down -v && rm -rf {remote_dir}'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {"success": False, "message": stderr.decode()}
        return {"success": True, "message": "OpenClaw instance removed"}
    except Exception as e:
        return {"success": False, "message": str(e)}


async def update_container_env(
    vps_host: str,
    ssh_key_path: str,
    instance_id: str,
    agent_name: str,
    agent_id: str,
    api_key: str,
    port: int,
    config_env: dict,
    ssh_user: str = "root",
    ssh_port: int = 22,
) -> dict:
    """
    Update a running OpenClaw instance with new env vars (e.g. LLM keys,
    integration tokens). Generates a new compose file and force-recreates
    the container.
    """
    if OPENCLAW_MOCK_MODE:
        return {"success": True, "message": "Container reconfigured (mock mode)"}

    compose = generate_compose(
        instance_id=instance_id,
        agent_name=agent_name,
        agent_id=agent_id,
        api_key=api_key,
        port=port,
        config_env=config_env,
    )

    remote_dir = f"/opt/hive/openclaw-{instance_id[:8]}"
    ssh_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -p {ssh_port}"
    )
    scp_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -P {ssh_port}"
    )
    target = f"{ssh_user}@{vps_host}"

    with tempfile.NamedTemporaryFile(mode="w", suffix=".yml", delete=False) as tmp:
        tmp.write(compose)
        local_compose = tmp.name

    try:
        # Copy updated compose file
        proc = await asyncio.create_subprocess_shell(
            f"scp {scp_opts} {local_compose} {target}:{remote_dir}/docker-compose.yml",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {"success": False, "message": f"scp failed: {stderr.decode()}"}

        # Force-recreate container with new env
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} "
            f"'cd {remote_dir} && docker compose up -d --force-recreate'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {"success": False, "message": f"docker compose up failed: {stderr.decode()}"}

        return {"success": True, "message": "Container reconfigured and restarted"}
    except Exception as e:
        return {"success": False, "message": str(e)}
    finally:
        os.unlink(local_compose)
